version: "1.0"
services:
  angular-app:
    image: angular-test:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/usr/src/app/src
    restart: always
