apiVersion: apps/v1
kind: Deployment
metadata:
  name: stnsoll-deployment
  labels:
    app: stnsoll
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stnsoll
  template:
    metadata:
      labels:
        app: stnsoll
    spec:
      containers:
      - name: stnsoll
        image: stnsoll:1.1
        ports:
        - containerPort: 80
